//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THE_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billsDetail
    {
        public int id { get; set; }
        public int products_id { get; set; }
        public int bills_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public decimal total_price { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
    }
}
