//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THE_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string notes { get; set; }
        public string phone { get; set; }
        public string company_name { get; set; }
        public string mail { get; set; }
        public bool is_active { get; set; }
        public string image { get; set; }
    }
}
